/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddressForm: typeof import('./components/AddressForm.vue')['default']
    DataCard: typeof import('./components/DataCard.vue')['default']
    FileUpload: typeof import('./components/FileUpload.vue')['default']
    ImagePreview: typeof import('./components/ImagePreview.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TrendChart: typeof import('./components/TrendChart.vue')['default']
  }
}
